# Generated by Django 3.2.11 on 2022-01-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_topicandcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topicandcomment',
        ),
    ]
