# Generated by Django 3.2.11 on 2022-01-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delete_topicandcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
