# Generated by Django 3.2.11 on 2022-01-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
