# Generated by Django 3.2.11 on 2022-01-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topicandcomment',
        ),
    ]
