# Generated by Django 3.2.11 on 2022-01-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topicandcomment',
        ),
    ]
