# Generated by Django 3.2.11 on 2022-01-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_topicandcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicandcomment',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Topicandcomment',
        ),
    ]
